name: Build Qt Project

on:
  push:
    branches:
      - main
      - buildbot

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: 6.8.2
        
    - name: Setup Cpp (C++ / C)
      # You may pin to the exact commit or the version.
      # uses: aminya/setup-cpp@290824452986e378826155f3379d31bce8753d76
      uses: aminya/setup-cpp@v0.37.0
      with:
        compiler: msvc
        architecture: x64
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: Configure using CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build
      
    - name: Run tests
      run: ctest --output-on-failure

    - name: Assemble output package
      run: copy D:\a\NASSPChecklistEditor\NasspChecklistEditor\build\Release\*.exe D:\a\NASSPChecklistEditor\NasspChecklistEditor\build\Release\package\
    - name: Bundle QT packages
      run: D:\a\NASSPchecklistEditor\Qt\6.8.2\msvc2022_64\bin\windeployqa.exe D:\a\NASSPChecklistEditor\NasspChecklistEditor\build\Release\package\TSVEditor.exe

    - name: Upload build artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: editor
        path: D:\a\NASSPchecklistEditor\NASSPchecklistEditor\build\Release\package\
