name: Build Qt Project

on:
  push:
    branches:
      - main
      - buildbot

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v4.1.1
      with:
        version: 6.8.2
    - name: install-cmake
      uses: Symbitic/install-cmake@v0.1.0

    - name: Configure using CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: ctest --output-on-failure
